// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNddWXuZu3B_2wFoPr2H75STcRZk4vTYs',
    appId: '1:145319049244:android:eecde85484f38c54f107d9',
    messagingSenderId: '145319049244',
    projectId: 'soocherv2',
    databaseURL: 'https://soocherv2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soocherv2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAelkwf9IDdFKXzy1OlhdTOhudJJutEnfs',
    appId: '1:145319049244:ios:46920ba73ba7112cf107d9',
    messagingSenderId: '145319049244',
    projectId: 'soocherv2',
    databaseURL: 'https://soocherv2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soocherv2.appspot.com',
    androidClientId: '145319049244-2i59f19bug1u8lsjtd8r5d9o7lb6hm5v.apps.googleusercontent.com',
    iosClientId: '145319049244-ped8tj7c5ef93kgcc06fcec5q4lsdsvs.apps.googleusercontent.com',
    iosBundleId: 'com.soocher.doctor.doctor',
  );
}
